# Generated by Django 5.2.6 on 2026-03-09 00:00

import django.db.models.deletion
from django.db import migrations, models


def seed_difficulties(apps, schema_editor):
    Difficulty = apps.get_model('quiz', 'Difficulty')
    Difficulty.objects.bulk_create(
        [
            Difficulty(code='easy', title='Лёгкий'),
            Difficulty(code='medium', title='Средний'),
            Difficulty(code='hard', title='Сложный'),
        ]
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        help_text='Краткое название категории',
                        max_length=100,
                        verbose_name='Название категории',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                (
                    'code',
                    models.CharField(
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                        verbose_name='Код сложности',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        max_length=32,
                        verbose_name='Название сложности',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Сложность',
                'verbose_name_plural': 'Сложности',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        help_text='Краткое название квиза',
                        max_length=200,
                        verbose_name='Название квиза',
                    ),
                ),
                (
                    'description',
                    models.CharField(
                        blank=True,
                        default='',
                        help_text='Короткое описание квиза',
                        max_length=500,
                        verbose_name='Описание квиза',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Квиз',
                'verbose_name_plural': 'Квизы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'text',
                    models.CharField(max_length=500, verbose_name='Текст вопроса'),
                ),
                (
                    'description',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=500,
                        verbose_name='Описание вопроса',
                    ),
                ),
                (
                    'correct_answer',
                    models.CharField(max_length=120, verbose_name='Правильный ответ'),
                ),
                (
                    'explanation',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=250,
                        verbose_name='Объяснение ответа',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='questions',
                        to='quiz.category',
                        verbose_name='Категория',
                    ),
                ),
                (
                    'difficulty',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='questions',
                        to='quiz.difficulty',
                        verbose_name='Сложность',
                    ),
                ),
                (
                    'quiz',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='questions',
                        to='quiz.quiz',
                        verbose_name='Квиз',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'text',
                    models.CharField(max_length=120, verbose_name='Текст варианта'),
                ),
                (
                    'position',
                    models.PositiveIntegerField(verbose_name='Позиция варианта'),
                ),
                (
                    'question',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='answer_options',
                        to='quiz.question',
                        verbose_name='Вопрос',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(
                fields=('question', 'position'),
                name='uniq_question_option_position',
            ),
        ),
        migrations.RunPython(seed_difficulties, migrations.RunPython.noop),
    ]
